### PR TITLE
Create Reader (story card 11)

### LINKED ISSUE #11: Create Reader Class
### Story
As a programmer, I want to read contents from chosen DOT files, so that the contents can be parsed.

### Demo Criteria
* Contents of a single file are represented by a single string
* Uses file path from Configuration class (#10)
* Returns a list of strings to Manager class (#9)

### Notes
* Resultant list of strings is not passed directly to parser, it is returned to the Manager which then hands individual strings (one by one, not as a collection) to parser

### PR DESCRIPTION
**Pull request by samanthacombs**

### CODE REVIEW

**Comment by spoofaloof** [comment]
update to reflect corrina's changes to the skeleton code

**Review by spoofaloof — APPROVED** [review]
leaving minor details for the merge

**Review by AVanDeBrook — APPROVED** [review]

**Review by corrinacoffee — APPROVED** [review]

**Comment by spoofaloof** [comment]
Both ways should work, but for checking the file to see if it is dot, I prefer the retVal way logic.

**Comment by spoofaloof** [comment]
I feel returns shouldn't be in if statements if possible

**Pull request merged**
